// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.impact.implementation;

import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.impact.fluent.models.WorkloadImpactInner;
import com.azure.resourcemanager.impact.models.WorkloadImpact;
import com.azure.resourcemanager.impact.models.WorkloadImpactProperties;

public final class WorkloadImpactImpl implements WorkloadImpact, WorkloadImpact.Definition {
    private WorkloadImpactInner innerObject;

    private final com.azure.resourcemanager.impact.ImpactManager serviceManager;

    WorkloadImpactImpl(WorkloadImpactInner innerObject, com.azure.resourcemanager.impact.ImpactManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public WorkloadImpactProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public WorkloadImpactInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.impact.ImpactManager manager() {
        return this.serviceManager;
    }

    private String workloadImpactName;

    public WorkloadImpact create() {
        this.innerObject = serviceManager.serviceClient()
            .getWorkloadImpacts()
            .create(workloadImpactName, this.innerModel(), Context.NONE);
        return this;
    }

    public WorkloadImpact create(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getWorkloadImpacts()
            .create(workloadImpactName, this.innerModel(), context);
        return this;
    }

    WorkloadImpactImpl(String name, com.azure.resourcemanager.impact.ImpactManager serviceManager) {
        this.innerObject = new WorkloadImpactInner();
        this.serviceManager = serviceManager;
        this.workloadImpactName = name;
    }

    public WorkloadImpact refresh() {
        this.innerObject = serviceManager.serviceClient()
            .getWorkloadImpacts()
            .getWithResponse(workloadImpactName, Context.NONE)
            .getValue();
        return this;
    }

    public WorkloadImpact refresh(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getWorkloadImpacts()
            .getWithResponse(workloadImpactName, context)
            .getValue();
        return this;
    }

    public WorkloadImpactImpl withProperties(WorkloadImpactProperties properties) {
        this.innerModel().withProperties(properties);
        return this;
    }
}
