// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.azure.resourcemanager.loadtestservicemicrosoftloadtestserviceplaywright {
    requires transitive com.azure.core.management;

    exports com.azure.resourcemanager.loadtestservicemicrosoftloadtestserviceplaywright;
    exports com.azure.resourcemanager.loadtestservicemicrosoftloadtestserviceplaywright.fluent;
    exports com.azure.resourcemanager.loadtestservicemicrosoftloadtestserviceplaywright.fluent.models;
    exports com.azure.resourcemanager.loadtestservicemicrosoftloadtestserviceplaywright.models;

    opens com.azure.resourcemanager.loadtestservicemicrosoftloadtestserviceplaywright.fluent.models to com.azure.core;
    opens com.azure.resourcemanager.loadtestservicemicrosoftloadtestserviceplaywright.models to com.azure.core;
}
