// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.search.documents.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.core.util.CoreUtils;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Represents the result of an individual indexer execution.
 */
@Immutable
public final class IndexerExecutionResult implements JsonSerializable<IndexerExecutionResult> {
    /*
     * The outcome of this indexer execution.
     */
    @Generated
    private final IndexerExecutionStatus status;

    /*
     * The outcome of this indexer execution.
     */
    @Generated
    private IndexerExecutionStatusDetail statusDetail;

    /*
     * All of the state that defines and dictates the indexer's current execution.
     */
    @Generated
    private IndexerCurrentState currentState;

    /*
     * The error message indicating the top-level error, if any.
     */
    @Generated
    private String errorMessage;

    /*
     * The start time of this indexer execution.
     */
    @Generated
    private OffsetDateTime startTime;

    /*
     * The end time of this indexer execution, if the execution has already completed.
     */
    @Generated
    private OffsetDateTime endTime;

    /*
     * The item-level indexing errors.
     */
    @Generated
    private final List<SearchIndexerError> errors;

    /*
     * The item-level indexing warnings.
     */
    @Generated
    private final List<SearchIndexerWarning> warnings;

    /*
     * The number of items that were processed during this indexer execution. This
     * includes both successfully processed items and items where indexing was
     * attempted but failed.
     */
    @Generated
    private final int itemCount;

    /*
     * The number of items that failed to be indexed during this indexer execution.
     */
    @Generated
    private final int failedItemCount;

    /*
     * Change tracking state with which an indexer execution started.
     */
    @Generated
    private String initialTrackingState;

    /*
     * Change tracking state with which an indexer execution finished.
     */
    @Generated
    private String finalTrackingState;

    /**
     * Creates an instance of IndexerExecutionResult class.
     * 
     * @param status the status value to set.
     * @param errors the errors value to set.
     * @param warnings the warnings value to set.
     * @param itemCount the itemCount value to set.
     * @param failedItemCount the failedItemCount value to set.
     */
    @Generated
    private IndexerExecutionResult(IndexerExecutionStatus status, List<SearchIndexerError> errors,
        List<SearchIndexerWarning> warnings, int itemCount, int failedItemCount) {
        this.status = status;
        this.errors = errors;
        this.warnings = warnings;
        this.itemCount = itemCount;
        this.failedItemCount = failedItemCount;
    }

    /**
     * Get the status property: The outcome of this indexer execution.
     * 
     * @return the status value.
     */
    @Generated
    public IndexerExecutionStatus getStatus() {
        return this.status;
    }

    /**
     * Get the statusDetail property: The outcome of this indexer execution.
     * 
     * @return the statusDetail value.
     */
    @Generated
    public IndexerExecutionStatusDetail getStatusDetail() {
        return this.statusDetail;
    }

    /**
     * Get the currentState property: All of the state that defines and dictates the indexer's current execution.
     * 
     * @return the currentState value.
     */
    @Generated
    public IndexerCurrentState getCurrentState() {
        return this.currentState;
    }

    /**
     * Get the errorMessage property: The error message indicating the top-level error, if any.
     * 
     * @return the errorMessage value.
     */
    @Generated
    public String getErrorMessage() {
        return this.errorMessage;
    }

    /**
     * Get the startTime property: The start time of this indexer execution.
     * 
     * @return the startTime value.
     */
    @Generated
    public OffsetDateTime getStartTime() {
        return this.startTime;
    }

    /**
     * Get the endTime property: The end time of this indexer execution, if the execution has already completed.
     * 
     * @return the endTime value.
     */
    @Generated
    public OffsetDateTime getEndTime() {
        return this.endTime;
    }

    /**
     * Get the errors property: The item-level indexing errors.
     * 
     * @return the errors value.
     */
    @Generated
    public List<SearchIndexerError> getErrors() {
        return this.errors;
    }

    /**
     * Get the warnings property: The item-level indexing warnings.
     * 
     * @return the warnings value.
     */
    @Generated
    public List<SearchIndexerWarning> getWarnings() {
        return this.warnings;
    }

    /**
     * Get the itemCount property: The number of items that were processed during this indexer execution. This
     * includes both successfully processed items and items where indexing was
     * attempted but failed.
     * 
     * @return the itemCount value.
     */
    @Generated
    public int getItemCount() {
        return this.itemCount;
    }

    /**
     * Get the failedItemCount property: The number of items that failed to be indexed during this indexer execution.
     * 
     * @return the failedItemCount value.
     */
    @Generated
    public int getFailedItemCount() {
        return this.failedItemCount;
    }

    /**
     * Get the initialTrackingState property: Change tracking state with which an indexer execution started.
     * 
     * @return the initialTrackingState value.
     */
    @Generated
    public String getInitialTrackingState() {
        return this.initialTrackingState;
    }

    /**
     * Get the finalTrackingState property: Change tracking state with which an indexer execution finished.
     * 
     * @return the finalTrackingState value.
     */
    @Generated
    public String getFinalTrackingState() {
        return this.finalTrackingState;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("status", this.status == null ? null : this.status.toString());
        jsonWriter.writeArrayField("errors", this.errors, (writer, element) -> writer.writeJson(element));
        jsonWriter.writeArrayField("warnings", this.warnings, (writer, element) -> writer.writeJson(element));
        jsonWriter.writeIntField("itemsProcessed", this.itemCount);
        jsonWriter.writeIntField("itemsFailed", this.failedItemCount);
        jsonWriter.writeStringField("errorMessage", this.errorMessage);
        jsonWriter.writeStringField("startTime",
            this.startTime == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.startTime));
        jsonWriter.writeStringField("endTime",
            this.endTime == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.endTime));
        jsonWriter.writeStringField("initialTrackingState", this.initialTrackingState);
        jsonWriter.writeStringField("finalTrackingState", this.finalTrackingState);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of IndexerExecutionResult from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of IndexerExecutionResult if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the IndexerExecutionResult.
     */
    @Generated
    public static IndexerExecutionResult fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            IndexerExecutionStatus status = null;
            List<SearchIndexerError> errors = null;
            List<SearchIndexerWarning> warnings = null;
            int itemCount = 0;
            int failedItemCount = 0;
            IndexerExecutionStatusDetail statusDetail = null;
            IndexerCurrentState currentState = null;
            String errorMessage = null;
            OffsetDateTime startTime = null;
            OffsetDateTime endTime = null;
            String initialTrackingState = null;
            String finalTrackingState = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("status".equals(fieldName)) {
                    status = IndexerExecutionStatus.fromString(reader.getString());
                } else if ("errors".equals(fieldName)) {
                    errors = reader.readArray(reader1 -> SearchIndexerError.fromJson(reader1));
                } else if ("warnings".equals(fieldName)) {
                    warnings = reader.readArray(reader1 -> SearchIndexerWarning.fromJson(reader1));
                } else if ("itemsProcessed".equals(fieldName)) {
                    itemCount = reader.getInt();
                } else if ("itemsFailed".equals(fieldName)) {
                    failedItemCount = reader.getInt();
                } else if ("statusDetail".equals(fieldName)) {
                    statusDetail = IndexerExecutionStatusDetail.fromString(reader.getString());
                } else if ("currentState".equals(fieldName)) {
                    currentState = IndexerCurrentState.fromJson(reader);
                } else if ("errorMessage".equals(fieldName)) {
                    errorMessage = reader.getString();
                } else if ("startTime".equals(fieldName)) {
                    startTime = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else if ("endTime".equals(fieldName)) {
                    endTime = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else if ("initialTrackingState".equals(fieldName)) {
                    initialTrackingState = reader.getString();
                } else if ("finalTrackingState".equals(fieldName)) {
                    finalTrackingState = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            IndexerExecutionResult deserializedIndexerExecutionResult
                = new IndexerExecutionResult(status, errors, warnings, itemCount, failedItemCount);
            deserializedIndexerExecutionResult.statusDetail = statusDetail;
            deserializedIndexerExecutionResult.currentState = currentState;
            deserializedIndexerExecutionResult.errorMessage = errorMessage;
            deserializedIndexerExecutionResult.startTime = startTime;
            deserializedIndexerExecutionResult.endTime = endTime;
            deserializedIndexerExecutionResult.initialTrackingState = initialTrackingState;
            deserializedIndexerExecutionResult.finalTrackingState = finalTrackingState;

            return deserializedIndexerExecutionResult;
        });
    }
}
