// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearning.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** Properties of a labeling job. */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "mediaType",
    defaultImpl = LabelingJobMediaProperties.class)
@JsonTypeName("LabelingJobMediaProperties")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "Image", value = LabelingJobImageProperties.class),
    @JsonSubTypes.Type(name = "Text", value = LabelingJobTextProperties.class)
})
@Immutable
public class LabelingJobMediaProperties {
    /** Creates an instance of LabelingJobMediaProperties class. */
    public LabelingJobMediaProperties() {
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
