// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearning.models;

import com.azure.core.annotation.Fluent;
import java.util.Map;

/** Managed service identity (system assigned and/or user assigned identities). */
@Fluent
public final class RegistryPartialManagedServiceIdentity extends ManagedServiceIdentity {
    /** Creates an instance of RegistryPartialManagedServiceIdentity class. */
    public RegistryPartialManagedServiceIdentity() {
    }

    /** {@inheritDoc} */
    @Override
    public RegistryPartialManagedServiceIdentity withType(ManagedServiceIdentityType type) {
        super.withType(type);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public RegistryPartialManagedServiceIdentity withUserAssignedIdentities(
        Map<String, UserAssignedIdentity> userAssignedIdentities) {
        super.withUserAssignedIdentities(userAssignedIdentities);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }
}
