// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearning.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** Spark job entry point definition. */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "sparkJobEntryType",
    defaultImpl = SparkJobEntry.class)
@JsonTypeName("SparkJobEntry")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "SparkJobPythonEntry", value = SparkJobPythonEntry.class),
    @JsonSubTypes.Type(name = "SparkJobScalaEntry", value = SparkJobScalaEntry.class)
})
@Immutable
public class SparkJobEntry {
    /** Creates an instance of SparkJobEntry class. */
    public SparkJobEntry() {
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
