// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearning.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** WorkspaceHub's configuration object. */
@Fluent
public final class WorkspaceHubConfig {
    /*
     * The additionalWorkspaceStorageAccounts property.
     */
    @JsonProperty(value = "additionalWorkspaceStorageAccounts")
    private List<String> additionalWorkspaceStorageAccounts;

    /*
     * The defaultWorkspaceResourceGroup property.
     */
    @JsonProperty(value = "defaultWorkspaceResourceGroup")
    private String defaultWorkspaceResourceGroup;

    /** Creates an instance of WorkspaceHubConfig class. */
    public WorkspaceHubConfig() {
    }

    /**
     * Get the additionalWorkspaceStorageAccounts property: The additionalWorkspaceStorageAccounts property.
     *
     * @return the additionalWorkspaceStorageAccounts value.
     */
    public List<String> additionalWorkspaceStorageAccounts() {
        return this.additionalWorkspaceStorageAccounts;
    }

    /**
     * Set the additionalWorkspaceStorageAccounts property: The additionalWorkspaceStorageAccounts property.
     *
     * @param additionalWorkspaceStorageAccounts the additionalWorkspaceStorageAccounts value to set.
     * @return the WorkspaceHubConfig object itself.
     */
    public WorkspaceHubConfig withAdditionalWorkspaceStorageAccounts(List<String> additionalWorkspaceStorageAccounts) {
        this.additionalWorkspaceStorageAccounts = additionalWorkspaceStorageAccounts;
        return this;
    }

    /**
     * Get the defaultWorkspaceResourceGroup property: The defaultWorkspaceResourceGroup property.
     *
     * @return the defaultWorkspaceResourceGroup value.
     */
    public String defaultWorkspaceResourceGroup() {
        return this.defaultWorkspaceResourceGroup;
    }

    /**
     * Set the defaultWorkspaceResourceGroup property: The defaultWorkspaceResourceGroup property.
     *
     * @param defaultWorkspaceResourceGroup the defaultWorkspaceResourceGroup value to set.
     * @return the WorkspaceHubConfig object itself.
     */
    public WorkspaceHubConfig withDefaultWorkspaceResourceGroup(String defaultWorkspaceResourceGroup) {
        this.defaultWorkspaceResourceGroup = defaultWorkspaceResourceGroup;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
