// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.apicenter.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * Api Deployment Server.
 */
@Immutable
public final class ApiDeploymentServer implements JsonSerializable<ApiDeploymentServer> {
    /*
     * Base runtime URIs for this deployment.
     */
    @Generated
    private final List<String> runtimeUris;

    /**
     * Creates an instance of ApiDeploymentServer class.
     * 
     * @param runtimeUris the runtimeUris value to set.
     */
    @Generated
    private ApiDeploymentServer(List<String> runtimeUris) {
        this.runtimeUris = runtimeUris;
    }

    /**
     * Get the runtimeUris property: Base runtime URIs for this deployment.
     * 
     * @return the runtimeUris value.
     */
    @Generated
    public List<String> getRuntimeUris() {
        return this.runtimeUris;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("runtimeUris", this.runtimeUris, (writer, element) -> writer.writeString(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ApiDeploymentServer from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ApiDeploymentServer if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the ApiDeploymentServer.
     */
    @Generated
    public static ApiDeploymentServer fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            List<String> runtimeUris = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("runtimeUris".equals(fieldName)) {
                    runtimeUris = reader.readArray(reader1 -> reader1.getString());
                } else {
                    reader.skipChildren();
                }
            }
            return new ApiDeploymentServer(runtimeUris);
        });
    }
}
