// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.recoveryservicesbackup.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Container Type - VM, SQLPaaS, DPM, AzureFileShare...
 */
public final class DataSourceTypeAutoGenerated2 extends ExpandableStringEnum<DataSourceTypeAutoGenerated2> {
    /**
     * Static value Invalid for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 INVALID = fromString("Invalid");

    /**
     * Static value VM for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 VM = fromString("VM");

    /**
     * Static value FileFolder for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 FILE_FOLDER = fromString("FileFolder");

    /**
     * Static value AzureSqlDb for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 AZURE_SQL_DB = fromString("AzureSqlDb");

    /**
     * Static value SQLDB for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 SQLDB = fromString("SQLDB");

    /**
     * Static value Exchange for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 EXCHANGE = fromString("Exchange");

    /**
     * Static value Sharepoint for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 SHAREPOINT = fromString("Sharepoint");

    /**
     * Static value VMwareVM for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 VMWARE_VM = fromString("VMwareVM");

    /**
     * Static value SystemState for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 SYSTEM_STATE = fromString("SystemState");

    /**
     * Static value Client for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 CLIENT = fromString("Client");

    /**
     * Static value GenericDataSource for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 GENERIC_DATA_SOURCE = fromString("GenericDataSource");

    /**
     * Static value SQLDataBase for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 SQLDATA_BASE = fromString("SQLDataBase");

    /**
     * Static value AzureFileShare for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 AZURE_FILE_SHARE = fromString("AzureFileShare");

    /**
     * Static value SAPHanaDatabase for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 SAPHANA_DATABASE = fromString("SAPHanaDatabase");

    /**
     * Static value SAPAseDatabase for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 SAPASE_DATABASE = fromString("SAPAseDatabase");

    /**
     * Static value SAPHanaDBInstance for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 SAPHANA_DBINSTANCE = fromString("SAPHanaDBInstance");

    /**
     * Static value OracleDatabase for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 ORACLE_DATABASE = fromString("OracleDatabase");

    /**
     * Static value AnyDatabase for DataSourceTypeAutoGenerated2.
     */
    public static final DataSourceTypeAutoGenerated2 ANY_DATABASE = fromString("AnyDatabase");

    /**
     * Creates a new instance of DataSourceTypeAutoGenerated2 value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public DataSourceTypeAutoGenerated2() {
    }

    /**
     * Creates or finds a DataSourceTypeAutoGenerated2 from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding DataSourceTypeAutoGenerated2.
     */
    public static DataSourceTypeAutoGenerated2 fromString(String name) {
        return fromString(name, DataSourceTypeAutoGenerated2.class);
    }

    /**
     * Gets known DataSourceTypeAutoGenerated2 values.
     * 
     * @return known DataSourceTypeAutoGenerated2 values.
     */
    public static Collection<DataSourceTypeAutoGenerated2> values() {
        return values(DataSourceTypeAutoGenerated2.class);
    }
}
