// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.language.text.authoring.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * Represents an exported document of a custom multi-label classification project.
 */
@Fluent
public final class TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument
    implements JsonSerializable<TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument> {
    /*
     * The document classes.
     */
    @Generated
    private List<TextAnalysisAuthoringExportedDocumentClass> classes;

    /*
     * The location of the document in the storage.
     */
    @Generated
    private String location;

    /*
     * Represents the document language. This is BCP-47 representation of a language. For example, use "en" for English,
     * "en-gb" for English (UK), "es" for Spanish etc.
     */
    @Generated
    private String language;

    /*
     * The dataset for this document. Allowed values are 'Train' and 'Test'.
     */
    @Generated
    private String dataset;

    /**
     * Creates an instance of TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument class.
     */
    @Generated
    public TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument() {
    }

    /**
     * Get the classes property: The document classes.
     * 
     * @return the classes value.
     */
    @Generated
    public List<TextAnalysisAuthoringExportedDocumentClass> getClasses() {
        return this.classes;
    }

    /**
     * Set the classes property: The document classes.
     * 
     * @param classes the classes value to set.
     * @return the TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument object itself.
     */
    @Generated
    public TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument
        setClasses(List<TextAnalysisAuthoringExportedDocumentClass> classes) {
        this.classes = classes;
        return this;
    }

    /**
     * Get the location property: The location of the document in the storage.
     * 
     * @return the location value.
     */
    @Generated
    public String getLocation() {
        return this.location;
    }

    /**
     * Set the location property: The location of the document in the storage.
     * 
     * @param location the location value to set.
     * @return the TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument object itself.
     */
    @Generated
    public TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument setLocation(String location) {
        this.location = location;
        return this;
    }

    /**
     * Get the language property: Represents the document language. This is BCP-47 representation of a language. For
     * example, use "en" for English, "en-gb" for English (UK), "es" for Spanish etc.
     * 
     * @return the language value.
     */
    @Generated
    public String getLanguage() {
        return this.language;
    }

    /**
     * Set the language property: Represents the document language. This is BCP-47 representation of a language. For
     * example, use "en" for English, "en-gb" for English (UK), "es" for Spanish etc.
     * 
     * @param language the language value to set.
     * @return the TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument object itself.
     */
    @Generated
    public TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument setLanguage(String language) {
        this.language = language;
        return this;
    }

    /**
     * Get the dataset property: The dataset for this document. Allowed values are 'Train' and 'Test'.
     * 
     * @return the dataset value.
     */
    @Generated
    public String getDataset() {
        return this.dataset;
    }

    /**
     * Set the dataset property: The dataset for this document. Allowed values are 'Train' and 'Test'.
     * 
     * @param dataset the dataset value to set.
     * @return the TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument object itself.
     */
    @Generated
    public TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument setDataset(String dataset) {
        this.dataset = dataset;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("classes", this.classes, (writer, element) -> writer.writeJson(element));
        jsonWriter.writeStringField("location", this.location);
        jsonWriter.writeStringField("language", this.language);
        jsonWriter.writeStringField("dataset", this.dataset);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument if the JsonReader was
     * pointing to an instance of it, or null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the
     * TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument.
     */
    @Generated
    public static TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument fromJson(JsonReader jsonReader)
        throws IOException {
        return jsonReader.readObject(reader -> {
            TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument deserializedTextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument
                = new TextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("classes".equals(fieldName)) {
                    List<TextAnalysisAuthoringExportedDocumentClass> classes
                        = reader.readArray(reader1 -> TextAnalysisAuthoringExportedDocumentClass.fromJson(reader1));
                    deserializedTextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument.classes = classes;
                } else if ("location".equals(fieldName)) {
                    deserializedTextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument.location
                        = reader.getString();
                } else if ("language".equals(fieldName)) {
                    deserializedTextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument.language
                        = reader.getString();
                } else if ("dataset".equals(fieldName)) {
                    deserializedTextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument.dataset
                        = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedTextAnalysisAuthoringExportedCustomMultiLabelClassificationDocument;
        });
    }
}
