// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.terraform.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * The Azure Resource Graph Authorization Scope Filter parameter.
 */
public final class AuthorizationScopeFilter extends ExpandableStringEnum<AuthorizationScopeFilter> {
    /**
     * Static value AtScopeAndBelow for AuthorizationScopeFilter.
     */
    public static final AuthorizationScopeFilter AT_SCOPE_AND_BELOW = fromString("AtScopeAndBelow");

    /**
     * Static value AtScopeAndAbove for AuthorizationScopeFilter.
     */
    public static final AuthorizationScopeFilter AT_SCOPE_AND_ABOVE = fromString("AtScopeAndAbove");

    /**
     * Static value AtScopeAboveAndBelow for AuthorizationScopeFilter.
     */
    public static final AuthorizationScopeFilter AT_SCOPE_ABOVE_AND_BELOW = fromString("AtScopeAboveAndBelow");

    /**
     * Static value AtScopeExact for AuthorizationScopeFilter.
     */
    public static final AuthorizationScopeFilter AT_SCOPE_EXACT = fromString("AtScopeExact");

    /**
     * Creates a new instance of AuthorizationScopeFilter value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public AuthorizationScopeFilter() {
    }

    /**
     * Creates or finds a AuthorizationScopeFilter from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding AuthorizationScopeFilter.
     */
    public static AuthorizationScopeFilter fromString(String name) {
        return fromString(name, AuthorizationScopeFilter.class);
    }

    /**
     * Gets known AuthorizationScopeFilter values.
     * 
     * @return known AuthorizationScopeFilter values.
     */
    public static Collection<AuthorizationScopeFilter> values() {
        return values(AuthorizationScopeFilter.class);
    }
}
