// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azuredatatransfer.models;

import com.azure.resourcemanager.azuredatatransfer.fluent.models.GetStreamConnectionStringResultInner;

/**
 * An immutable client-side representation of GetStreamConnectionStringResult.
 */
public interface GetStreamConnectionStringResult {
    /**
     * Gets the connectionString property: The connection string for the specified streaming flow.
     * 
     * @return the connectionString value.
     */
    String connectionString();

    /**
     * Gets the inner com.azure.resourcemanager.azuredatatransfer.fluent.models.GetStreamConnectionStringResultInner
     * object.
     * 
     * @return the inner object.
     */
    GetStreamConnectionStringResultInner innerModel();
}
