// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azuredatatransfer.models;

import com.azure.core.management.SystemData;
import com.azure.resourcemanager.azuredatatransfer.fluent.models.PendingFlowInner;
import java.util.List;
import java.util.Map;

/**
 * An immutable client-side representation of PendingFlow.
 */
public interface PendingFlow {
    /**
     * Gets the connection property: The connection associated with this flow.
     * 
     * @return the connection value.
     */
    SelectedResource connection();

    /**
     * Gets the flowId property: Dataflow GUID associated with this flow.
     * 
     * @return the flowId value.
     */
    String flowId();

    /**
     * Gets the keyVaultUri property: AME, PME, or TORUS only! AKV Chain Containing SAS Token.
     * 
     * @return the keyVaultUri value.
     */
    String keyVaultUri();

    /**
     * Gets the linkStatus property: Link status of the current flow.
     * 
     * @return the linkStatus value.
     */
    LinkStatusFlow linkStatus();

    /**
     * Gets the linkedFlowId property: Resource ID of the linked flow.
     * 
     * @return the linkedFlowId value.
     */
    String linkedFlowId();

    /**
     * Gets the status property: Status of the current flow.
     * 
     * @return the status value.
     */
    FlowStatus status();

    /**
     * Gets the forceDisabledStatus property: Force disablement status of the current flow.
     * 
     * @return the forceDisabledStatus value.
     */
    List<ForceDisabledStatus> forceDisabledStatus();

    /**
     * Gets the storageAccountName property: Storage Account.
     * 
     * @return the storageAccountName value.
     */
    String storageAccountName();

    /**
     * Gets the storageAccountId property: Storage Account ID.
     * 
     * @return the storageAccountId value.
     */
    String storageAccountId();

    /**
     * Gets the storageContainerName property: Storage Container Name.
     * 
     * @return the storageContainerName value.
     */
    String storageContainerName();

    /**
     * Gets the storageTableName property: Storage Table Name.
     * 
     * @return the storageTableName value.
     */
    String storageTableName();

    /**
     * Gets the serviceBusQueueId property: Service Bus Queue ID.
     * 
     * @return the serviceBusQueueId value.
     */
    String serviceBusQueueId();

    /**
     * Gets the flowType property: The flow type for this flow.
     * 
     * @return the flowType value.
     */
    FlowType flowType();

    /**
     * Gets the dataType property: Transfer Storage Blobs or Tables.
     * 
     * @return the dataType value.
     */
    DataType dataType();

    /**
     * Gets the provisioningState property: Provisioning state of the flow.
     * 
     * @return the provisioningState value.
     */
    ProvisioningState provisioningState();

    /**
     * Gets the policies property: The policies for this flow.
     * 
     * @return the policies value.
     */
    List<String> policies();

    /**
     * Gets the schema property: The selected schema for this flow.
     * 
     * @return the schema value.
     */
    Schema schema();

    /**
     * Gets the messagingOptions property: The messaging options for this flow.
     * 
     * @return the messagingOptions value.
     */
    MessagingOptions messagingOptions();

    /**
     * Gets the apiFlowOptions property: The API Flow configuration options for Azure Data Transfer API Flow type.
     * 
     * @return the apiFlowOptions value.
     */
    ApiFlowOptions apiFlowOptions();

    /**
     * Gets the customerManagedKeyVaultUri property: The URI to the customer managed key for this flow.
     * 
     * @return the customerManagedKeyVaultUri value.
     */
    String customerManagedKeyVaultUri();

    /**
     * Gets the streamId property: The flow stream identifier.
     * 
     * @return the streamId value.
     */
    String streamId();

    /**
     * Gets the streamProtocol property: The protocol of the stream.
     * 
     * @return the streamProtocol value.
     */
    StreamProtocol streamProtocol();

    /**
     * Gets the streamLatency property: The latency of the stream in milliseconds.
     * 
     * @return the streamLatency value.
     */
    Long streamLatency();

    /**
     * Gets the passphrase property: The passphrase used for SRT streams.
     * 
     * @return the passphrase value.
     */
    String passphrase();

    /**
     * Gets the sourceAddresses property: The source IP address and CIDR ranges of the stream.
     * 
     * @return the sourceAddresses value.
     */
    StreamSourceAddresses sourceAddresses();

    /**
     * Gets the destinationEndpoints property: The destination endpoints of the stream.
     * 
     * @return the destinationEndpoints value.
     */
    List<String> destinationEndpoints();

    /**
     * Gets the destinationEndpointPorts property: The destination endpoint ports of the stream.
     * 
     * @return the destinationEndpointPorts value.
     */
    List<Long> destinationEndpointPorts();

    /**
     * Gets the eventHubId property: Event Hub ID.
     * 
     * @return the eventHubId value.
     */
    String eventHubId();

    /**
     * Gets the consumerGroup property: Event Hub Consumer Group.
     * 
     * @return the consumerGroup value.
     */
    String consumerGroup();

    /**
     * Gets the subscriptionId property: Subscription ID of the pending flow.
     * 
     * @return the subscriptionId value.
     */
    String subscriptionId();

    /**
     * Gets the connectionId property: Connection ID of the pending flow.
     * 
     * @return the connectionId value.
     */
    String connectionId();

    /**
     * Gets the tags property: Resource tags.
     * 
     * @return the tags value.
     */
    Map<String, String> tags();

    /**
     * Gets the location property: The geo-location where the resource lives.
     * 
     * @return the location value.
     */
    String location();

    /**
     * Gets the systemData property: Azure Resource Manager metadata containing createdBy and modifiedBy information.
     * 
     * @return the systemData value.
     */
    SystemData systemData();

    /**
     * Gets the id property: the fully qualified resource ID for the resource.
     * 
     * @return the id value.
     */
    String id();

    /**
     * Gets the name property: the name of the resource.
     * 
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: the type of the resource.
     * 
     * @return the type value.
     */
    String type();

    /**
     * Gets the inner com.azure.resourcemanager.azuredatatransfer.fluent.models.PendingFlowInner object.
     * 
     * @return the inner object.
     */
    PendingFlowInner innerModel();
}
