// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.logic.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * The flow template type.
 */
public final class FlowTemplateType extends ExpandableStringEnum<FlowTemplateType> {
    /**
     * Static value NotSpecified for FlowTemplateType.
     */
    public static final FlowTemplateType NOT_SPECIFIED = fromString("NotSpecified");

    /**
     * Static value Workflow for FlowTemplateType.
     */
    public static final FlowTemplateType WORKFLOW = fromString("Workflow");

    /**
     * Static value Accelerator for FlowTemplateType.
     */
    public static final FlowTemplateType ACCELERATOR = fromString("Accelerator");

    /**
     * Creates a new instance of FlowTemplateType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public FlowTemplateType() {
    }

    /**
     * Creates or finds a FlowTemplateType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding FlowTemplateType.
     */
    public static FlowTemplateType fromString(String name) {
        return fromString(name, FlowTemplateType.class);
    }

    /**
     * Gets known FlowTemplateType values.
     * 
     * @return known FlowTemplateType values.
     */
    public static Collection<FlowTemplateType> values() {
        return values(FlowTemplateType.class);
    }
}
