// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.advisor.models;

import com.azure.resourcemanager.advisor.fluent.models.AdvisorScoreResponseInner;
import java.util.List;

/**
 * An immutable client-side representation of AdvisorScoreResponse.
 */
public interface AdvisorScoreResponse {
    /**
     * Gets the value property: The list of operations.
     * 
     * @return the value value.
     */
    List<AdvisorScoreEntity> value();

    /**
     * Gets the inner com.azure.resourcemanager.advisor.fluent.models.AdvisorScoreResponseInner object.
     * 
     * @return the inner object.
     */
    AdvisorScoreResponseInner innerModel();
}
