// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.notificationhubs.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.notificationhubs.fluent.PrivateEndpointConnectionResourcesClient;
import com.azure.resourcemanager.notificationhubs.fluent.models.PrivateEndpointConnectionResourceInner;
import com.azure.resourcemanager.notificationhubs.models.PrivateEndpointConnectionResource;
import com.azure.resourcemanager.notificationhubs.models.PrivateEndpointConnectionResources;

public final class PrivateEndpointConnectionResourcesImpl implements PrivateEndpointConnectionResources {
    private static final ClientLogger LOGGER = new ClientLogger(PrivateEndpointConnectionResourcesImpl.class);

    private final PrivateEndpointConnectionResourcesClient innerClient;

    private final com.azure.resourcemanager.notificationhubs.NotificationhubsManager serviceManager;

    public PrivateEndpointConnectionResourcesImpl(PrivateEndpointConnectionResourcesClient innerClient,
        com.azure.resourcemanager.notificationhubs.NotificationhubsManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public Response<PrivateEndpointConnectionResource> getWithResponse(String resourceGroupName, String namespaceName,
        String privateEndpointConnectionName, Context context) {
        Response<PrivateEndpointConnectionResourceInner> inner = this.serviceClient()
            .getWithResponse(resourceGroupName, namespaceName, privateEndpointConnectionName, context);
        if (inner != null) {
            return new SimpleResponse<>(inner.getRequest(), inner.getStatusCode(), inner.getHeaders(),
                new PrivateEndpointConnectionResourceImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    public PrivateEndpointConnectionResource get(String resourceGroupName, String namespaceName,
        String privateEndpointConnectionName) {
        PrivateEndpointConnectionResourceInner inner
            = this.serviceClient().get(resourceGroupName, namespaceName, privateEndpointConnectionName);
        if (inner != null) {
            return new PrivateEndpointConnectionResourceImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public PrivateEndpointConnectionResource update(String resourceGroupName, String namespaceName,
        String privateEndpointConnectionName, PrivateEndpointConnectionResourceInner parameters) {
        PrivateEndpointConnectionResourceInner inner
            = this.serviceClient().update(resourceGroupName, namespaceName, privateEndpointConnectionName, parameters);
        if (inner != null) {
            return new PrivateEndpointConnectionResourceImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public PrivateEndpointConnectionResource update(String resourceGroupName, String namespaceName,
        String privateEndpointConnectionName, PrivateEndpointConnectionResourceInner parameters, Context context) {
        PrivateEndpointConnectionResourceInner inner = this.serviceClient()
            .update(resourceGroupName, namespaceName, privateEndpointConnectionName, parameters, context);
        if (inner != null) {
            return new PrivateEndpointConnectionResourceImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public void delete(String resourceGroupName, String namespaceName, String privateEndpointConnectionName) {
        this.serviceClient().delete(resourceGroupName, namespaceName, privateEndpointConnectionName);
    }

    public void delete(String resourceGroupName, String namespaceName, String privateEndpointConnectionName,
        Context context) {
        this.serviceClient().delete(resourceGroupName, namespaceName, privateEndpointConnectionName, context);
    }

    public PagedIterable<PrivateEndpointConnectionResource> list(String resourceGroupName, String namespaceName) {
        PagedIterable<PrivateEndpointConnectionResourceInner> inner
            = this.serviceClient().list(resourceGroupName, namespaceName);
        return ResourceManagerUtils.mapPage(inner,
            inner1 -> new PrivateEndpointConnectionResourceImpl(inner1, this.manager()));
    }

    public PagedIterable<PrivateEndpointConnectionResource> list(String resourceGroupName, String namespaceName,
        Context context) {
        PagedIterable<PrivateEndpointConnectionResourceInner> inner
            = this.serviceClient().list(resourceGroupName, namespaceName, context);
        return ResourceManagerUtils.mapPage(inner,
            inner1 -> new PrivateEndpointConnectionResourceImpl(inner1, this.manager()));
    }

    private PrivateEndpointConnectionResourcesClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.notificationhubs.NotificationhubsManager manager() {
        return this.serviceManager;
    }
}
