// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.desktopvirtualization.models;

import com.azure.core.management.exception.ManagementError;
import com.azure.resourcemanager.desktopvirtualization.fluent.models.SessionHostManagementProvisioningStatusInner;
import java.time.OffsetDateTime;

/**
 * An immutable client-side representation of SessionHostManagementProvisioningStatus.
 */
public interface SessionHostManagementProvisioningStatus {
    /**
     * Gets the id property: Fully qualified ID for the async operation.
     * 
     * @return the id value.
     */
    String id();

    /**
     * Gets the name property: Name of the async operation.
     * 
     * @return the name value.
     */
    String name();

    /**
     * Gets the status property: Operation status. Current defined values are &lt; Scheduled |
     * ValidatingSessionHostProvisioning | Cancelling | ProvisioningSessionHosts &gt; | Succeeded | Failed | Canceled.
     * 
     * @return the status value.
     */
    String status();

    /**
     * Gets the percentComplete property: Percent of the operation that is complete.
     * 
     * @return the percentComplete value.
     */
    Float percentComplete();

    /**
     * Gets the startTime property: The start time of the operation.
     * 
     * @return the startTime value.
     */
    OffsetDateTime startTime();

    /**
     * Gets the endTime property: The end time of the operation.
     * 
     * @return the endTime value.
     */
    OffsetDateTime endTime();

    /**
     * Gets the error property: If present, details of the operation error.
     * 
     * @return the error value.
     */
    ManagementError error();

    /**
     * Gets the correlationId property: The correlation Id for Log Analytics.
     * 
     * @return the correlationId value.
     */
    String correlationId();

    /**
     * Gets the progress property: Progress information on the sessionHostManagement operation.
     * 
     * @return the progress value.
     */
    SessionHostManagementProvisioningOperationProgress progress();

    /**
     * Gets the scheduledDateTime property: The timestamp that the update is scheduled for.
     * 
     * @return the scheduledDateTime value.
     */
    OffsetDateTime scheduledDateTime();

    /**
     * Gets the sessionHostManagement property: SessionHostManagement properties used for the operation.
     * 
     * @return the sessionHostManagement value.
     */
    SessionHostManagement sessionHostManagement();

    /**
     * Gets the inner
     * com.azure.resourcemanager.desktopvirtualization.fluent.models.SessionHostManagementProvisioningStatusInner
     * object.
     * 
     * @return the inner object.
     */
    SessionHostManagementProvisioningStatusInner innerModel();
}
