// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azuredatatransfer.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.azuredatatransfer.fluent.ConnectionsClient;
import com.azure.resourcemanager.azuredatatransfer.fluent.models.ConnectionInner;
import com.azure.resourcemanager.azuredatatransfer.fluent.models.PendingConnectionInner;
import com.azure.resourcemanager.azuredatatransfer.fluent.models.PendingFlowInner;
import com.azure.resourcemanager.azuredatatransfer.models.Connection;
import com.azure.resourcemanager.azuredatatransfer.models.Connections;
import com.azure.resourcemanager.azuredatatransfer.models.PendingConnection;
import com.azure.resourcemanager.azuredatatransfer.models.PendingFlow;
import com.azure.resourcemanager.azuredatatransfer.models.ResourceBody;

public final class ConnectionsImpl implements Connections {
    private static final ClientLogger LOGGER = new ClientLogger(ConnectionsImpl.class);

    private final ConnectionsClient innerClient;

    private final com.azure.resourcemanager.azuredatatransfer.AzuredatatransferManager serviceManager;

    public ConnectionsImpl(ConnectionsClient innerClient,
        com.azure.resourcemanager.azuredatatransfer.AzuredatatransferManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public PagedIterable<Connection> listBySubscription() {
        PagedIterable<ConnectionInner> inner = this.serviceClient().listBySubscription();
        return ResourceManagerUtils.mapPage(inner, inner1 -> new ConnectionImpl(inner1, this.manager()));
    }

    public PagedIterable<Connection> listBySubscription(Context context) {
        PagedIterable<ConnectionInner> inner = this.serviceClient().listBySubscription(context);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new ConnectionImpl(inner1, this.manager()));
    }

    public PagedIterable<Connection> listByResourceGroup(String resourceGroupName) {
        PagedIterable<ConnectionInner> inner = this.serviceClient().listByResourceGroup(resourceGroupName);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new ConnectionImpl(inner1, this.manager()));
    }

    public PagedIterable<Connection> listByResourceGroup(String resourceGroupName, Context context) {
        PagedIterable<ConnectionInner> inner = this.serviceClient().listByResourceGroup(resourceGroupName, context);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new ConnectionImpl(inner1, this.manager()));
    }

    public Response<Connection> getByResourceGroupWithResponse(String resourceGroupName, String connectionName,
        Context context) {
        Response<ConnectionInner> inner
            = this.serviceClient().getByResourceGroupWithResponse(resourceGroupName, connectionName, context);
        if (inner != null) {
            return new SimpleResponse<>(inner.getRequest(), inner.getStatusCode(), inner.getHeaders(),
                new ConnectionImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    public Connection getByResourceGroup(String resourceGroupName, String connectionName) {
        ConnectionInner inner = this.serviceClient().getByResourceGroup(resourceGroupName, connectionName);
        if (inner != null) {
            return new ConnectionImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public void deleteByResourceGroup(String resourceGroupName, String connectionName) {
        this.serviceClient().delete(resourceGroupName, connectionName);
    }

    public void delete(String resourceGroupName, String connectionName, Context context) {
        this.serviceClient().delete(resourceGroupName, connectionName, context);
    }

    public Connection link(String resourceGroupName, String connectionName, ResourceBody body) {
        ConnectionInner inner = this.serviceClient().link(resourceGroupName, connectionName, body);
        if (inner != null) {
            return new ConnectionImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Connection link(String resourceGroupName, String connectionName, ResourceBody body, Context context) {
        ConnectionInner inner = this.serviceClient().link(resourceGroupName, connectionName, body, context);
        if (inner != null) {
            return new ConnectionImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public PagedIterable<PendingConnection> list(String resourceGroupName, String connectionName) {
        PagedIterable<PendingConnectionInner> inner = this.serviceClient().list(resourceGroupName, connectionName);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new PendingConnectionImpl(inner1, this.manager()));
    }

    public PagedIterable<PendingConnection> list(String resourceGroupName, String connectionName, Context context) {
        PagedIterable<PendingConnectionInner> inner
            = this.serviceClient().list(resourceGroupName, connectionName, context);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new PendingConnectionImpl(inner1, this.manager()));
    }

    public PagedIterable<PendingFlow> listPendingFlowsList(String resourceGroupName, String connectionName) {
        PagedIterable<PendingFlowInner> inner
            = this.serviceClient().listPendingFlowsList(resourceGroupName, connectionName);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new PendingFlowImpl(inner1, this.manager()));
    }

    public PagedIterable<PendingFlow> listPendingFlowsList(String resourceGroupName, String connectionName,
        Context context) {
        PagedIterable<PendingFlowInner> inner
            = this.serviceClient().listPendingFlowsList(resourceGroupName, connectionName, context);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new PendingFlowImpl(inner1, this.manager()));
    }

    public Connection getById(String id) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String connectionName = ResourceManagerUtils.getValueFromIdByName(id, "connections");
        if (connectionName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'connections'.", id)));
        }
        return this.getByResourceGroupWithResponse(resourceGroupName, connectionName, Context.NONE).getValue();
    }

    public Response<Connection> getByIdWithResponse(String id, Context context) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String connectionName = ResourceManagerUtils.getValueFromIdByName(id, "connections");
        if (connectionName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'connections'.", id)));
        }
        return this.getByResourceGroupWithResponse(resourceGroupName, connectionName, context);
    }

    public void deleteById(String id) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String connectionName = ResourceManagerUtils.getValueFromIdByName(id, "connections");
        if (connectionName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'connections'.", id)));
        }
        this.delete(resourceGroupName, connectionName, Context.NONE);
    }

    public void deleteByIdWithResponse(String id, Context context) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String connectionName = ResourceManagerUtils.getValueFromIdByName(id, "connections");
        if (connectionName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'connections'.", id)));
        }
        this.delete(resourceGroupName, connectionName, context);
    }

    private ConnectionsClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.azuredatatransfer.AzuredatatransferManager manager() {
        return this.serviceManager;
    }

    public ConnectionImpl define(String name) {
        return new ConnectionImpl(name, this.manager());
    }
}
