// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.migrate.implementation;

import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.migrate.fluent.models.CompoundAssessmentInner;
import com.azure.resourcemanager.migrate.models.CompoundAssessment;
import com.azure.resourcemanager.migrate.models.CompoundAssessmentProperties;
import com.azure.resourcemanager.migrate.models.DownloadUrl;
import com.azure.resourcemanager.migrate.models.DownloadUrlRequest;

public final class CompoundAssessmentImpl implements CompoundAssessment, CompoundAssessment.Definition {
    private CompoundAssessmentInner innerObject;

    private final com.azure.resourcemanager.migrate.MigrateManager serviceManager;

    CompoundAssessmentImpl(CompoundAssessmentInner innerObject,
        com.azure.resourcemanager.migrate.MigrateManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public CompoundAssessmentProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public CompoundAssessmentInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.migrate.MigrateManager manager() {
        return this.serviceManager;
    }

    private String resourceGroupName;

    private String projectName;

    private String compoundAssessmentName;

    public CompoundAssessmentImpl withExistingAssessmentProject(String resourceGroupName, String projectName) {
        this.resourceGroupName = resourceGroupName;
        this.projectName = projectName;
        return this;
    }

    public CompoundAssessment create() {
        this.innerObject = serviceManager.serviceClient()
            .getCompoundAssessmentOperations()
            .create(resourceGroupName, projectName, compoundAssessmentName, this.innerModel(), Context.NONE);
        return this;
    }

    public CompoundAssessment create(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getCompoundAssessmentOperations()
            .create(resourceGroupName, projectName, compoundAssessmentName, this.innerModel(), context);
        return this;
    }

    CompoundAssessmentImpl(String name, com.azure.resourcemanager.migrate.MigrateManager serviceManager) {
        this.innerObject = new CompoundAssessmentInner();
        this.serviceManager = serviceManager;
        this.compoundAssessmentName = name;
    }

    public CompoundAssessment refresh() {
        this.innerObject = serviceManager.serviceClient()
            .getCompoundAssessmentOperations()
            .getWithResponse(resourceGroupName, projectName, compoundAssessmentName, Context.NONE)
            .getValue();
        return this;
    }

    public CompoundAssessment refresh(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getCompoundAssessmentOperations()
            .getWithResponse(resourceGroupName, projectName, compoundAssessmentName, context)
            .getValue();
        return this;
    }

    public DownloadUrl downloadUrl(DownloadUrlRequest body) {
        return serviceManager.compoundAssessmentOperations()
            .downloadUrl(resourceGroupName, projectName, compoundAssessmentName, body);
    }

    public DownloadUrl downloadUrl(DownloadUrlRequest body, Context context) {
        return serviceManager.compoundAssessmentOperations()
            .downloadUrl(resourceGroupName, projectName, compoundAssessmentName, body, context);
    }

    public CompoundAssessmentImpl withProperties(CompoundAssessmentProperties properties) {
        this.innerModel().withProperties(properties);
        return this;
    }
}
