// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.cognitiveservices.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Internal use only. */
@Fluent
public final class DeploymentCapacitySettings {
    /*
     * The designated capacity.
     */
    @JsonProperty(value = "designatedCapacity")
    private Integer designatedCapacity;

    /*
     * The priority of this capacity setting.
     */
    @JsonProperty(value = "priority")
    private Integer priority;

    /** Creates an instance of DeploymentCapacitySettings class. */
    public DeploymentCapacitySettings() {
    }

    /**
     * Get the designatedCapacity property: The designated capacity.
     *
     * @return the designatedCapacity value.
     */
    public Integer designatedCapacity() {
        return this.designatedCapacity;
    }

    /**
     * Set the designatedCapacity property: The designated capacity.
     *
     * @param designatedCapacity the designatedCapacity value to set.
     * @return the DeploymentCapacitySettings object itself.
     */
    public DeploymentCapacitySettings withDesignatedCapacity(Integer designatedCapacity) {
        this.designatedCapacity = designatedCapacity;
        return this;
    }

    /**
     * Get the priority property: The priority of this capacity setting.
     *
     * @return the priority value.
     */
    public Integer priority() {
        return this.priority;
    }

    /**
     * Set the priority property: The priority of this capacity setting.
     *
     * @param priority the priority value to set.
     * @return the DeploymentCapacitySettings object itself.
     */
    public DeploymentCapacitySettings withPriority(Integer priority) {
        this.priority = priority;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
