// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.cognitiveservices.models;

import com.azure.core.annotation.Fluent;
import com.azure.resourcemanager.cognitiveservices.fluent.models.RaiBlocklistItemInner;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The list of cognitive services RAI Blocklist Items. */
@Fluent
public final class RaiBlockListItemsResult {
    /*
     * The link used to get the next page of RaiBlocklistItems.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /*
     * The list of RaiBlocklistItems.
     */
    @JsonProperty(value = "value")
    private List<RaiBlocklistItemInner> value;

    /** Creates an instance of RaiBlockListItemsResult class. */
    public RaiBlockListItemsResult() {
    }

    /**
     * Get the nextLink property: The link used to get the next page of RaiBlocklistItems.
     *
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: The link used to get the next page of RaiBlocklistItems.
     *
     * @param nextLink the nextLink value to set.
     * @return the RaiBlockListItemsResult object itself.
     */
    public RaiBlockListItemsResult withNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }

    /**
     * Get the value property: The list of RaiBlocklistItems.
     *
     * @return the value value.
     */
    public List<RaiBlocklistItemInner> value() {
        return this.value;
    }

    /**
     * Set the value property: The list of RaiBlocklistItems.
     *
     * @param value the value value to set.
     * @return the RaiBlockListItemsResult object itself.
     */
    public RaiBlockListItemsResult withValue(List<RaiBlocklistItemInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() != null) {
            value().forEach(e -> e.validate());
        }
    }
}
