// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.securityinsights.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** State of recommendation. */
public final class State extends ExpandableStringEnum<State> {
    /** Static value Active for State. */
    public static final State ACTIVE = fromString("Active");

    /** Static value Disabled for State. */
    public static final State DISABLED = fromString("Disabled");

    /** Static value CompletedByUser for State. */
    public static final State COMPLETED_BY_USER = fromString("CompletedByUser");

    /** Static value CompletedByAction for State. */
    public static final State COMPLETED_BY_ACTION = fromString("CompletedByAction");

    /** Static value Hidden for State. */
    public static final State HIDDEN = fromString("Hidden");

    /**
     * Creates a new instance of State value.
     *
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public State() {
    }

    /**
     * Creates or finds a State from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding State.
     */
    @JsonCreator
    public static State fromString(String name) {
        return fromString(name, State.class);
    }

    /**
     * Gets known State values.
     *
     * @return known State values.
     */
    public static Collection<State> values() {
        return values(State.class);
    }
}
