// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.securityinsights.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.securityinsights.fluent.ProductTemplatesClient;
import com.azure.resourcemanager.securityinsights.fluent.models.ProductTemplateModelInner;
import com.azure.resourcemanager.securityinsights.models.ProductTemplateModel;
import com.azure.resourcemanager.securityinsights.models.ProductTemplates;

public final class ProductTemplatesImpl implements ProductTemplates {
    private static final ClientLogger LOGGER = new ClientLogger(ProductTemplatesImpl.class);

    private final ProductTemplatesClient innerClient;

    private final com.azure.resourcemanager.securityinsights.SecurityInsightsManager serviceManager;

    public ProductTemplatesImpl(
        ProductTemplatesClient innerClient,
        com.azure.resourcemanager.securityinsights.SecurityInsightsManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public PagedIterable<ProductTemplateModel> list(String resourceGroupName, String workspaceName) {
        PagedIterable<ProductTemplateModelInner> inner = this.serviceClient().list(resourceGroupName, workspaceName);
        return Utils.mapPage(inner, inner1 -> new ProductTemplateModelImpl(inner1, this.manager()));
    }

    public PagedIterable<ProductTemplateModel> list(
        String resourceGroupName,
        String workspaceName,
        String filter,
        String orderby,
        String search,
        Boolean count,
        Integer top,
        Integer skip,
        String skipToken,
        Context context) {
        PagedIterable<ProductTemplateModelInner> inner =
            this
                .serviceClient()
                .list(resourceGroupName, workspaceName, filter, orderby, search, count, top, skip, skipToken, context);
        return Utils.mapPage(inner, inner1 -> new ProductTemplateModelImpl(inner1, this.manager()));
    }

    private ProductTemplatesClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.securityinsights.SecurityInsightsManager manager() {
        return this.serviceManager;
    }
}
