// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.apicenter;

import com.azure.core.util.ServiceVersion;

/**
 * Service version of DataApiClient.
 */
public enum DataApiServiceVersion implements ServiceVersion {
    /**
     * Enum value 2024-02-01-preview.
     */
    V2024_02_01_PREVIEW("2024-02-01-preview");

    private final String version;

    DataApiServiceVersion(String version) {
        this.version = version;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getVersion() {
        return this.version;
    }

    /**
     * Gets the latest service version supported by this client library.
     * 
     * @return The latest {@link DataApiServiceVersion}.
     */
    public static DataApiServiceVersion getLatest() {
        return V2024_02_01_PREVIEW;
    }
}
