// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.maintenance.fluent;

import com.azure.core.http.HttpPipeline;
import java.time.Duration;

/**
 * The interface for MaintenanceClient class.
 */
public interface MaintenanceClient {
    /**
     * Gets Service host.
     * 
     * @return the endpoint value.
     */
    String getEndpoint();

    /**
     * Gets Version parameter.
     * 
     * @return the apiVersion value.
     */
    String getApiVersion();

    /**
     * Gets The ID of the target subscription. The value must be an UUID.
     * 
     * @return the subscriptionId value.
     */
    String getSubscriptionId();

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    HttpPipeline getHttpPipeline();

    /**
     * Gets The default poll interval for long-running operation.
     * 
     * @return the defaultPollInterval value.
     */
    Duration getDefaultPollInterval();

    /**
     * Gets the OperationsClient object to access its operations.
     * 
     * @return the OperationsClient object.
     */
    OperationsClient getOperations();

    /**
     * Gets the MaintenanceConfigurationsClient object to access its operations.
     * 
     * @return the MaintenanceConfigurationsClient object.
     */
    MaintenanceConfigurationsClient getMaintenanceConfigurations();

    /**
     * Gets the MaintenanceConfigurationOperationGroupsClient object to access its operations.
     * 
     * @return the MaintenanceConfigurationOperationGroupsClient object.
     */
    MaintenanceConfigurationOperationGroupsClient getMaintenanceConfigurationOperationGroups();

    /**
     * Gets the ApplyUpdatesClient object to access its operations.
     * 
     * @return the ApplyUpdatesClient object.
     */
    ApplyUpdatesClient getApplyUpdates();

    /**
     * Gets the ApplyUpdateOperationGroupsClient object to access its operations.
     * 
     * @return the ApplyUpdateOperationGroupsClient object.
     */
    ApplyUpdateOperationGroupsClient getApplyUpdateOperationGroups();

    /**
     * Gets the ConfigurationAssignmentsClient object to access its operations.
     * 
     * @return the ConfigurationAssignmentsClient object.
     */
    ConfigurationAssignmentsClient getConfigurationAssignments();

    /**
     * Gets the ConfigurationAssignmentOperationGroupsClient object to access its operations.
     * 
     * @return the ConfigurationAssignmentOperationGroupsClient object.
     */
    ConfigurationAssignmentOperationGroupsClient getConfigurationAssignmentOperationGroups();

    /**
     * Gets the ConfigurationAssignmentsForSubscriptionsClient object to access its operations.
     * 
     * @return the ConfigurationAssignmentsForSubscriptionsClient object.
     */
    ConfigurationAssignmentsForSubscriptionsClient getConfigurationAssignmentsForSubscriptions();

    /**
     * Gets the ConfigurationAssignmentsForResourceGroupsClient object to access its operations.
     * 
     * @return the ConfigurationAssignmentsForResourceGroupsClient object.
     */
    ConfigurationAssignmentsForResourceGroupsClient getConfigurationAssignmentsForResourceGroups();

    /**
     * Gets the ScheduledEventOperationGroupsClient object to access its operations.
     * 
     * @return the ScheduledEventOperationGroupsClient object.
     */
    ScheduledEventOperationGroupsClient getScheduledEventOperationGroups();

    /**
     * Gets the ApplyUpdatesOperationGroupsClient object to access its operations.
     * 
     * @return the ApplyUpdatesOperationGroupsClient object.
     */
    ApplyUpdatesOperationGroupsClient getApplyUpdatesOperationGroups();

    /**
     * Gets the ApplyUpdateForResourceGroupOperationGroupsClient object to access its operations.
     * 
     * @return the ApplyUpdateForResourceGroupOperationGroupsClient object.
     */
    ApplyUpdateForResourceGroupOperationGroupsClient getApplyUpdateForResourceGroupOperationGroups();

    /**
     * Gets the ConfigurationAssignmentForResourceGroupOperationGroupsClient object to access its operations.
     * 
     * @return the ConfigurationAssignmentForResourceGroupOperationGroupsClient object.
     */
    ConfigurationAssignmentForResourceGroupOperationGroupsClient
        getConfigurationAssignmentForResourceGroupOperationGroups();

    /**
     * Gets the UpdatesOperationGroupsClient object to access its operations.
     * 
     * @return the UpdatesOperationGroupsClient object.
     */
    UpdatesOperationGroupsClient getUpdatesOperationGroups();
}
