// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.devopsinfrastructure.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * The certificate store name type.
 */
public final class CertificateStoreNameOption extends ExpandableStringEnum<CertificateStoreNameOption> {
    /**
     * Static value My for CertificateStoreNameOption.
     */
    public static final CertificateStoreNameOption MY = fromString("My");

    /**
     * Static value Root for CertificateStoreNameOption.
     */
    public static final CertificateStoreNameOption ROOT = fromString("Root");

    /**
     * Creates a new instance of CertificateStoreNameOption value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public CertificateStoreNameOption() {
    }

    /**
     * Creates or finds a CertificateStoreNameOption from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding CertificateStoreNameOption.
     */
    public static CertificateStoreNameOption fromString(String name) {
        return fromString(name, CertificateStoreNameOption.class);
    }

    /**
     * Gets known CertificateStoreNameOption values.
     * 
     * @return known CertificateStoreNameOption values.
     */
    public static Collection<CertificateStoreNameOption> values() {
        return values(CertificateStoreNameOption.class);
    }
}
