// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.language.text.authoring.implementation;

import com.azure.ai.language.text.authoring.AuthoringServiceVersion;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;

/**
 * Initializes a new instance of the AuthoringClient type.
 */
public final class AuthoringClientImpl {
    /**
     * Supported Cognitive Services endpoint e.g., https://&lt;resource-name&gt;.api.cognitiveservices.azure.com.
     */
    private final String endpoint;

    /**
     * Gets Supported Cognitive Services endpoint e.g., https://&lt;resource-name&gt;.api.cognitiveservices.azure.com.
     * 
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Service version.
     */
    private final AuthoringServiceVersion serviceVersion;

    /**
     * Gets Service version.
     * 
     * @return the serviceVersion value.
     */
    public AuthoringServiceVersion getServiceVersion() {
        return this.serviceVersion;
    }

    /**
     * The HTTP pipeline to send requests through.
     */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /**
     * The serializer to serialize an object into a string.
     */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     * 
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /**
     * The TextAnalysisAuthoringsImpl object to access its operations.
     */
    private final TextAnalysisAuthoringsImpl textAnalysisAuthorings;

    /**
     * Gets the TextAnalysisAuthoringsImpl object to access its operations.
     * 
     * @return the TextAnalysisAuthoringsImpl object.
     */
    public TextAnalysisAuthoringsImpl getTextAnalysisAuthorings() {
        return this.textAnalysisAuthorings;
    }

    /**
     * Initializes an instance of AuthoringClient client.
     * 
     * @param endpoint Supported Cognitive Services endpoint e.g.,
     * https://&lt;resource-name&gt;.api.cognitiveservices.azure.com.
     * @param serviceVersion Service version.
     */
    public AuthoringClientImpl(String endpoint, AuthoringServiceVersion serviceVersion) {
        this(new HttpPipelineBuilder().policies(new UserAgentPolicy(), new RetryPolicy()).build(),
            JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of AuthoringClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint Supported Cognitive Services endpoint e.g.,
     * https://&lt;resource-name&gt;.api.cognitiveservices.azure.com.
     * @param serviceVersion Service version.
     */
    public AuthoringClientImpl(HttpPipeline httpPipeline, String endpoint, AuthoringServiceVersion serviceVersion) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of AuthoringClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param endpoint Supported Cognitive Services endpoint e.g.,
     * https://&lt;resource-name&gt;.api.cognitiveservices.azure.com.
     * @param serviceVersion Service version.
     */
    public AuthoringClientImpl(HttpPipeline httpPipeline, SerializerAdapter serializerAdapter, String endpoint,
        AuthoringServiceVersion serviceVersion) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.endpoint = endpoint;
        this.serviceVersion = serviceVersion;
        this.textAnalysisAuthorings = new TextAnalysisAuthoringsImpl(this);
    }
}
