// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.maintenance.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.maintenance.fluent.ApplyUpdateForResourceGroupOperationGroupsClient;
import com.azure.resourcemanager.maintenance.fluent.models.ApplyUpdateInner;
import com.azure.resourcemanager.maintenance.models.ApplyUpdate;
import com.azure.resourcemanager.maintenance.models.ApplyUpdateForResourceGroupOperationGroups;

public final class ApplyUpdateForResourceGroupOperationGroupsImpl
    implements ApplyUpdateForResourceGroupOperationGroups {
    private static final ClientLogger LOGGER = new ClientLogger(ApplyUpdateForResourceGroupOperationGroupsImpl.class);

    private final ApplyUpdateForResourceGroupOperationGroupsClient innerClient;

    private final com.azure.resourcemanager.maintenance.MaintenanceManager serviceManager;

    public ApplyUpdateForResourceGroupOperationGroupsImpl(ApplyUpdateForResourceGroupOperationGroupsClient innerClient,
        com.azure.resourcemanager.maintenance.MaintenanceManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public PagedIterable<ApplyUpdate> listByResourceGroup(String resourceGroupName) {
        PagedIterable<ApplyUpdateInner> inner = this.serviceClient().listByResourceGroup(resourceGroupName);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new ApplyUpdateImpl(inner1, this.manager()));
    }

    public PagedIterable<ApplyUpdate> listByResourceGroup(String resourceGroupName, Context context) {
        PagedIterable<ApplyUpdateInner> inner = this.serviceClient().listByResourceGroup(resourceGroupName, context);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new ApplyUpdateImpl(inner1, this.manager()));
    }

    private ApplyUpdateForResourceGroupOperationGroupsClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.maintenance.MaintenanceManager manager() {
        return this.serviceManager;
    }
}
