// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the service clients for DesktopVirtualizationApiClient.
 * This Typespec represents the Desktop Virtualization API interfaces.
 */
package com.azure.resourcemanager.desktopvirtualization.fluent;
