// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.migrate.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Migration Workload type.
 */
public final class MigrateWorkloadType extends ExpandableStringEnum<MigrateWorkloadType> {
    /**
     * Unknown - Migration Workload type.
     */
    public static final MigrateWorkloadType UNKNOWN = fromString("Unknown");

    /**
     * Machine - Migration Workload type.
     */
    public static final MigrateWorkloadType MACHINE = fromString("Machine");

    /**
     * Server - Migration Workload type.
     */
    public static final MigrateWorkloadType SERVER = fromString("Server");

    /**
     * Instance - Migration Workload type.
     */
    public static final MigrateWorkloadType INSTANCE = fromString("Instance");

    /**
     * WebServer - Migration Workload type.
     */
    public static final MigrateWorkloadType WEB_SERVER = fromString("WebServer");

    /**
     * WebApplication - Migration Workload type.
     */
    public static final MigrateWorkloadType WEB_APPLICATION = fromString("WebApplication");

    /**
     * Database - Migration Workload type.
     */
    public static final MigrateWorkloadType DATABASE = fromString("Database");

    /**
     * Host - Migration Workload type.
     */
    public static final MigrateWorkloadType HOST = fromString("Host");

    /**
     * ManagementServer - Migration Workload type.
     */
    public static final MigrateWorkloadType MANAGEMENT_SERVER = fromString("ManagementServer");

    /**
     * Creates a new instance of MigrateWorkloadType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public MigrateWorkloadType() {
    }

    /**
     * Creates or finds a MigrateWorkloadType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding MigrateWorkloadType.
     */
    public static MigrateWorkloadType fromString(String name) {
        return fromString(name, MigrateWorkloadType.class);
    }

    /**
     * Gets known MigrateWorkloadType values.
     * 
     * @return known MigrateWorkloadType values.
     */
    public static Collection<MigrateWorkloadType> values() {
        return values(MigrateWorkloadType.class);
    }
}
