# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/containerregistry/ci.yml
      - sdk/containerregistry/azure-containers-containerregistry/
      - sdk/containerregistry/azure-containers-containerregistry-perf/
    exclude:
      - sdk/containerregistry/pom.xml
      - sdk/containerregistry/azure-containers-containerregistry/pom.xml
      - sdk/containerregistry/azure-containers-containerregistry-perf/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/containerregistry/ci.yml
      - sdk/containerregistry/azure-containers-containerregistry/
      - sdk/containerregistry/azure-containers-containerregistry-perf/
    exclude:
      - sdk/containerregistry/pom.xml
      - sdk/containerregistry/azure-containers-containerregistry/pom.xml
      - sdk/containerregistry/azure-containers-containerregistry-perf/pom.xml

parameters:
  - name: release_dependsonlivetests
    displayName: Release depends on live tests
    type: boolean
    default: true
  - name: release_azureresourcemanagercontainerregistrygenerated
    displayName: azure-resourcemanager-containerregistry-generated
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: containerregistry
    EnableBatchRelease: true
    Artifacts:
      - name: azure-containers-containerregistry
        groupId: com.azure
        safeName: azurecontainerscontainerregistry
      - name: azure-resourcemanager-containerregistry-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercontainerregistrygenerated
        releaseInBatch: ${{ parameters.release_azureresourcemanagercontainerregistrygenerated }}
    AdditionalModules:
      - name: azure-containers-containerregistry-perf
        groupId: com.azure
      - name: perf-test-core
        groupId: com.azure
