// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.databasefleetmanager.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * The provisioning state of the resource.
 */
public final class AzureProvisioningState extends ExpandableStringEnum<AzureProvisioningState> {
    /**
     * Static value Succeeded for AzureProvisioningState.
     */
    public static final AzureProvisioningState SUCCEEDED = fromString("Succeeded");

    /**
     * Static value Failed for AzureProvisioningState.
     */
    public static final AzureProvisioningState FAILED = fromString("Failed");

    /**
     * Static value Canceled for AzureProvisioningState.
     */
    public static final AzureProvisioningState CANCELED = fromString("Canceled");

    /**
     * Static value Provisioning for AzureProvisioningState.
     */
    public static final AzureProvisioningState PROVISIONING = fromString("Provisioning");

    /**
     * Static value Accepted for AzureProvisioningState.
     */
    public static final AzureProvisioningState ACCEPTED = fromString("Accepted");

    /**
     * Creates a new instance of AzureProvisioningState value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public AzureProvisioningState() {
    }

    /**
     * Creates or finds a AzureProvisioningState from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding AzureProvisioningState.
     */
    public static AzureProvisioningState fromString(String name) {
        return fromString(name, AzureProvisioningState.class);
    }

    /**
     * Gets known AzureProvisioningState values.
     * 
     * @return known AzureProvisioningState values.
     */
    public static Collection<AzureProvisioningState> values() {
        return values(AzureProvisioningState.class);
    }
}
