// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.databasefleetmanager.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Resource type of the destination tier override.
 */
public final class ResourceType extends ExpandableStringEnum<ResourceType> {
    /**
     * Static value Database for ResourceType.
     */
    public static final ResourceType DATABASE = fromString("Database");

    /**
     * Static value Pool for ResourceType.
     */
    public static final ResourceType POOL = fromString("Pool");

    /**
     * Creates a new instance of ResourceType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public ResourceType() {
    }

    /**
     * Creates or finds a ResourceType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding ResourceType.
     */
    public static ResourceType fromString(String name) {
        return fromString(name, ResourceType.class);
    }

    /**
     * Gets known ResourceType values.
     * 
     * @return known ResourceType values.
     */
    public static Collection<ResourceType> values() {
        return values(ResourceType.class);
    }
}
